platform :ios, '14.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', '7.4.4'
  pod 'CapacitorCordova', '7.4.4'
  pod 'CapacitorApp', :path => '../LocalPods/CapacitorApp'
  pod 'CapacitorBrowser', :path => '../LocalPods/CapacitorBrowser'
  pod 'CapacitorPreferences', :path => '../LocalPods/CapacitorPreferences'
  pod 'CapacitorShare', :path => '../LocalPods/CapacitorShare'
  pod 'CapacitorCommunityHttp', :path => '../LocalPods/CapacitorCommunityHttp'
end

target 'App' do
  capacitor_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
