/**
 * MongoDB Atlas `ppamong` 클러스터 카탈로그.
 * 런타임 DB 이름: MONGODB_DB_NAME 또는 기본 `ppamong`.
 * 컬렉션 이름은 Mongoose 기본 복수형(Stadium만 `stadia`).
 */
export const MONGO_CATALOG_UPDATED = "2026-08-27";

export const MONGO_CLUSTER = {
  product: "PPAMONG (빠몽이)",
  cluster: "ppamong clusters (MongoDB Atlas)",
  database: "ppamong",
  envUri: "MONGODB_URI",
  envDbName: "MONGODB_DB_NAME",
  note:
    "연결은 mongoose.connect(uri, { dbName }). URI 경로에 DB가 있어도 dbName 옵션이 우선합니다. PostgreSQL/Drizzle는 레거시 마이그레이션용이며 런타임에 쓰지 않습니다.",
  redisNote:
    "세션·인증코드·광고 보상 중복방지·휴대폰 인증은 Redis 키입니다. Mongo 컬렉션이 아닙니다.",
} as const;

export interface MongoFieldDoc {
  name: string;
  type: string;
  role: string;
  values?: string;
}

export interface MongoCollectionDoc {
  area: string;
  model: string;
  collection: string;
  role: string;
  fields: MongoFieldDoc[];
  indexes?: string[];
  notes?: string[];
}

export const MONGO_COLLECTIONS: MongoCollectionDoc[] = [
  {
    area: "인프라",
    model: "Counter",
    collection: "counters",
    role: "숫자 id 채번 (게시글·주문·예측 등)",
    fields: [
      { name: "name", type: "string", role: "시퀀스 키", values: "unique" },
      { name: "value", type: "number", role: "마지막 발급 값" },
    ],
  },
  {
    area: "회원",
    model: "User",
    collection: "users",
    role: "앱 회원·게스트 계정과 보유 포인트",
    fields: [
      { name: "id", type: "string", role: "앱 사용자 UUID", values: "unique, 필수" },
      { name: "username", type: "string", role: "로그인 아이디", values: "unique" },
      { name: "name", type: "string", role: "표시 이름" },
      { name: "password", type: "string|null", role: "해시 비밀번호. 소셜은 null" },
      { name: "passwordPlain", type: "string", role: "운영 복구용 평문(레거시). 신규는 비움 권장" },
      { name: "phone", type: "string", role: "휴대폰", values: "sparse unique" },
      { name: "email", type: "string|null", role: "이메일" },
      { name: "provider", type: "string", role: "가입 경로", values: "local|kakao|google|apple|guest" },
      { name: "providerId", type: "string", role: "소셜/게스트 고유 ID. 게스트는 UUID" },
      { name: "inviteCode", type: "string", role: "내 초대코드 6자리", values: "sparse unique" },
      { name: "referralCode", type: "string|null", role: "가입 시 입력한 추천인 코드" },
      { name: "verificationCode", type: "string|null", role: "SMS 인증 코드(폴백 표시용)" },
      { name: "verificationCodeExpiry", type: "Date|null", role: "인증 코드 만료" },
      { name: "points", type: "number", role: "보유 포인트. 타석·사이드벳·광고 보상 반영" },
      { name: "lastAttendanceDate", type: "Date|null", role: "마지막 출석일" },
      { name: "isSuspended", type: "number", role: "1이면 정지(소프트 삭제)" },
      { name: "suspendedAt", type: "Date|null", role: "정지 시각" },
      { name: "isOnline", type: "number", role: "최근 온라인 표시. 1=온라인" },
      { name: "lastLogin", type: "Date|null", role: "마지막 로그인" },
      { name: "lastLogout", type: "Date|null", role: "마지막 로그아웃" },
      { name: "lastActive", type: "Date|null", role: "keepAlive·활동 ping" },
      { name: "totalDonationAmount", type: "number", role: "기부 누적 포인트" },
      { name: "dataSource", type: "string", role: "ppamong | badminton9 등 출처" },
      { name: "createdAt", type: "Date", role: "가입 시각" },
    ],
    indexes: ["unique(provider, providerId) sparse"],
  },
  {
    area: "회원",
    model: "AttendanceRecord",
    collection: "attendancerecords",
    role: "일일 출석 기록",
    fields: [
      { name: "id", type: "number", role: "출석 레코드 번호" },
      { name: "userId", type: "string", role: "users.id" },
      { name: "attendanceDate", type: "Date", role: "출석 날짜" },
    ],
  },
  {
    area: "회원",
    model: "PointTransaction",
    collection: "pointtransactions",
    role: "포인트 증감 원장",
    fields: [
      { name: "id", type: "number", role: "거래 번호" },
      { name: "userId", type: "string", role: "users.id" },
      { name: "transactionType", type: "string", role: "earned|spent|donation|donated_spent 등" },
      { name: "amount", type: "number", role: "양수=적립, 음수=사용" },
      { name: "balance", type: "number", role: "거래 후 잔액" },
      { name: "description", type: "string", role: "타석 적중, 사이드벳, 광고 등 설명" },
      { name: "createdAt", type: "Date", role: "시각" },
    ],
  },
  {
    area: "경기",
    model: "Stadium",
    collection: "stadia",
    role: "구장 마스터. Mongoose 복수형이 stadiums가 아니라 stadia",
    fields: [
      { name: "id", type: "number", role: "구장 번호. Match.stadiumId가 참조" },
      { name: "name", type: "string", role: "고척, 잠실 등 표시명", values: "unique" },
      { name: "createdAt", type: "Date", role: "등록 시각" },
    ],
    notes: ["컬렉션 이름이 stadia 입니다. stadiums로 조회하면 비어 있습니다."],
  },
  {
    area: "경기",
    model: "Match",
    collection: "matches",
    role: "오늘 KBO 경기·실황 스냅샷·운영자 타석 커서. 예측 게임의 중심 문서",
    fields: [
      { name: "id", type: "string", role: "경기 UUID. WS·예측·사이드벳 키" },
      { name: "name", type: "string", role: "제N경기 등 표시명" },
      { name: "stadiumId", type: "number", role: "stadia.id" },
      { name: "matchDate", type: "string|null", role: "KST YYYY-MM-DD" },
      { name: "startTime", type: "Date", role: "예정 시작. 예측 버튼은 이 시각 5분 전부터" },
      { name: "endTime", type: "Date", role: "예정 종료" },
      {
        name: "matchStatus",
        type: "string",
        role: "scheduled|ongoing|completed|cancelled. ongoing은 다음 스포츠 실황만",
      },
      { name: "currentRound", type: "number", role: "타석 라운드 번호" },
      {
        name: "predictionEnabled",
        type: "boolean",
        role: "운영자 「예측 시작」이 켠 타석 창. matchStatus를 올리지 않음",
      },
      {
        name: "liveAutoEnabled",
        type: "boolean",
        role: "실황 타석 힌트 ON. UI 토글 없음. 기본 true",
      },
      { name: "registrationOrder", type: "number|null", role: "제1~5 슬롯 순서" },
      { name: "apiSportsGameId", type: "number|null", role: "레거시. 실황에 쓰지 않음" },
      { name: "daumGameId", type: "number|null", role: "다음 스포츠 경기 ID. 점수·일정 연동" },
      { name: "apiSportsHomeTeam", type: "string|null", role: "홈 팀명 (필드명 레거시)" },
      { name: "apiSportsAwayTeam", type: "string|null", role: "원정 팀명 (필드명 레거시)" },
      { name: "apiSportsHomeTeamId", type: "number|null", role: "홈 팀 ID (레거시 이름)" },
      { name: "apiSportsAwayTeamId", type: "number|null", role: "원정 팀 ID (레거시 이름)" },
      { name: "apiSportsHomeTeamLogo", type: "string|null", role: "홈 로고 URL (다음 스포츠)" },
      { name: "apiSportsAwayTeamLogo", type: "string|null", role: "원정 로고 URL (다음 스포츠)" },
      {
        name: "liveScoreboard",
        type: "Mixed",
        role: "실황 보드. 득점·이닝표=다음, 주자·B-S·OUT·타자=네이버. 구조는 LiveScoreboard",
      },
      { name: "lastInningKey", type: "string|null", role: "이닝 키 캐시" },
      {
        name: "controlMode",
        type: "string",
        role: "auto=다음 점수 덮어씀, manual=운영자/관리자 PATCH 점수 유지",
      },
      { name: "sideBetsLocked", type: "boolean", role: "1회 시작 시 사이드벳 마감" },
      { name: "gameInning", type: "number", role: "운영자 기준 이닝(1=1회). 표시는 실황 우선" },
      { name: "inningHalf", type: "string", role: "top=초(원정), bottom=말(홈)" },
      { name: "batterIndexInHalf", type: "number", role: "현재 공격 팀 타순 1~9" },
      { name: "awayBatterOrder", type: "number", role: "원정(초) 타순 커서 1~9" },
      { name: "homeBatterOrder", type: "number", role: "홈(말) 타순 커서 1~9" },
      {
        name: "outsInHalf",
        type: "number",
        role: "운영자 누적 아웃. 3아웃 카운트·예측 종료 권위. 공수교대는 네이버 3아웃 대기(강제 가능)",
      },
      { name: "pinchHitter", type: "Mixed|null", role: "현재 타석 대타. 다음타자·공수 시 해제, 투수교체 유지" },
      { name: "matchLineup", type: "Mixed|null", role: "선발 타순 스냅샷 (네이버)" },
      { name: "matchPlayerStats", type: "Mixed|null", role: "타자 시즌 스탯 캐시" },
      { name: "matchHeadToHead", type: "Mixed|null", role: "상대전적 awayWins/homeWins" },
      { name: "matchTeamSeasonStats", type: "Mixed|null", role: "팀 시즌 성적(순위·승무패)" },
      { name: "createdAt", type: "Date", role: "등록 시각" },
    ],
    notes: [
      "실황 ON은 Match 필드가 아니라 AdminUser.apiSyncEnabled(운영자 슬롯)입니다. 회원 선택 모달의 sideBetEnabled는 API가 붙입니다.",
      "atBatPhase는 Match에 저장하지 않고 RoundStatistics + predictionEnabled로 도출합니다.",
    ],
  },
  {
    area: "경기",
    model: "ApiSportsScheduleCache",
    collection: "apisportsschedulecaches",
    role: "일정 캐시 문서. 이름은 레거시이며 값은 다음 스포츠 일정으로 채움",
    fields: [
      { name: "matchDate", type: "string", role: "날짜 키 YYYY-MM-DD" },
      { name: "apiSportsGameId", type: "number", role: "외부 경기 ID (레거시 필드명, 값은 다음 스포츠)" },
      { name: "season", type: "number|null", role: "시즌 연도" },
      { name: "leagueId", type: "number", role: "리그 ID. 기본 5(KBO 레거시)" },
      { name: "date", type: "string", role: "일정 날짜 원문" },
      { name: "time", type: "string", role: "시작 시각 문자열" },
      { name: "timestamp", type: "number", role: "유닉스 시각" },
      { name: "statusShort", type: "string", role: "NS, LIVE, FT, BEFORE 등" },
      { name: "statusLong", type: "string", role: "상태 설명" },
      { name: "homeTeamId", type: "number|null", role: "홈 팀 ID" },
      { name: "homeTeamName", type: "string", role: "홈 팀명" },
      { name: "awayTeamId", type: "number|null", role: "원정 팀 ID" },
      { name: "awayTeamName", type: "string", role: "원정 팀명" },
      { name: "venueName", type: "string", role: "구장명" },
      { name: "venueCity", type: "string", role: "도시" },
      { name: "homeScore", type: "number", role: "홈 점수 캐시" },
      { name: "awayScore", type: "number", role: "원정 점수 캐시" },
      { name: "fetchedAt", type: "Date", role: "수집 시각" },
    ],
    indexes: ["unique(matchDate, apiSportsGameId)"],
  },
  {
    area: "경기",
    model: "KboPlayer",
    collection: "kboplayers",
    role: "KBO 선수 마스터(타율 등). 선발명단·대타 검색",
    fields: [
      { name: "id", type: "string", role: "선수 문서 ID" },
      { name: "team", type: "string", role: "소속 팀명" },
      { name: "season", type: "number", role: "시즌 연도" },
      { name: "name", type: "string", role: "선수명" },
      { name: "position", type: "string", role: "포지션" },
      { name: "jerseyNumber", type: "string", role: "등번호" },
      { name: "batsThrows", type: "string", role: "타석/투구 손" },
      { name: "battingAverage", type: "string|null", role: "타율 표시" },
      { name: "hits", type: "number|null", role: "안타" },
      { name: "homeRuns", type: "number|null", role: "홈런" },
      { name: "rbi", type: "number|null", role: "타점" },
      { name: "ops", type: "string|null", role: "OPS" },
      { name: "note", type: "string", role: "메모" },
      { name: "active", type: "boolean", role: "현역 여부" },
      { name: "apiSportsPlayerId", type: "number|null", role: "레거시 외부 ID" },
      { name: "createdAt", type: "Date", role: "등록" },
      { name: "updatedAt", type: "Date", role: "갱신" },
    ],
    indexes: ["unique(team, season, name)", "partial unique(season, apiSportsPlayerId)"],
  },
  {
    area: "예측",
    model: "Prediction",
    collection: "predictions",
    role: "타석(라운드) 한 건의 회원 예측",
    fields: [
      { name: "id", type: "number", role: "예측 번호" },
      { name: "userId", type: "string", role: "users.id" },
      { name: "matchId", type: "string", role: "matches.id" },
      { name: "roundNumber", type: "number", role: "타석 라운드. Match.currentRound와 대응" },
      { name: "prediction", type: "string", role: "아웃|1루|2루|3루|홈런" },
      { name: "amount", type: "number", role: "건 포인트 50~1000" },
      { name: "status", type: "string", role: "pending|success|fail" },
      { name: "result", type: "string|null", role: "확정 결과. 투수교체 환불 시 생략 가능" },
      { name: "wonAmount", type: "number", role: "적중 시 지급액 = amount × 배당" },
      { name: "donatedAmount", type: "number", role: "기부 처리분" },
      { name: "createdAt", type: "Date", role: "제출 시각" },
    ],
    indexes: ["unique(userId, matchId, roundNumber) — 한 타석 한 번"],
  },
  {
    area: "예측",
    model: "RoundStatistics",
    collection: "roundstatistics",
    role: "타석 라운드 상태. atBatPhase 도출의 근거",
    fields: [
      { name: "id", type: "number", role: "라운드 통계 ID" },
      { name: "matchId", type: "string", role: "matches.id" },
      { name: "roundNumber", type: "number", role: "라운드 번호" },
      { name: "totalParticipants", type: "number", role: "참여자 수" },
      { name: "totalPoints", type: "number", role: "해당 라운드 총 포인트" },
      { name: "totalWinners", type: "number", role: "적중자 수" },
      { name: "predictionStartTime", type: "Date|null", role: "창 열림" },
      { name: "predictionStopTime", type: "Date|null", role: "창 닫힘" },
      { name: "isPredictionStarted", type: "boolean", role: "예측 시작 여부" },
      { name: "isPredictionStopped", type: "boolean", role: "예측 중지 여부" },
      { name: "isResultSent", type: "boolean", role: "결과 확정 여부" },
      { name: "settledResult", type: "string|null", role: "확정 결과. UI stage=result 복원" },
      { name: "createdAt", type: "Date", role: "생성" },
    ],
    notes: [
      "idle / prediction_open / prediction_closed / result_confirmed 는 이 플래그 + Match.predictionEnabled로 계산합니다.",
    ],
  },
  {
    area: "예측",
    model: "MatchSideBet",
    collection: "matchsidebets",
    role: "경기 단위 사이드벳(우승팀·최종 스코어). 1회 시작 전 마감",
    fields: [
      { name: "id", type: "number", role: "사이드벳 번호" },
      { name: "userId / matchId", type: "string", role: "회원·경기" },
      { name: "type", type: "string", role: "winner | score" },
      { name: "winnerPick", type: "home|away|null", role: "우승팀 선택" },
      { name: "homeScorePick / awayScorePick", type: "number|null", role: "최종 스코어 선택" },
      { name: "amount", type: "number", role: "건 포인트" },
      { name: "odds", type: "number", role: "우승팀 2배, 스코어 20배" },
      { name: "status", type: "string", role: "pending|success|fail" },
      { name: "wonAmount", type: "number", role: "정산 지급" },
      { name: "createdAt", type: "Date", role: "접수 시각" },
    ],
    indexes: ["unique(userId, matchId, type)"],
  },
  {
    area: "운영",
    model: "AdminUser",
    collection: "adminusers",
    role: "슈퍼어드민·일반어드민·운영자 계정",
    fields: [
      { name: "id", type: "string", role: "스태프 UUID" },
      { name: "email", type: "string", role: "로그인 이메일", values: "unique" },
      { name: "username", type: "string", role: "로그인 아이디", values: "unique" },
      { name: "name", type: "string", role: "표시 이름" },
      { name: "phone", type: "string", role: "연락처" },
      { name: "department", type: "string|null", role: "부서" },
      { name: "position", type: "string|null", role: "직책" },
      { name: "password", type: "string", role: "해시 비밀번호" },
      { name: "passwordPlain", type: "string", role: "운영 복구용 평문(주의)" },
      { name: "userType", type: "string", role: "슈퍼어드민|일반어드민|운영자" },
      { name: "approvalStatus", type: "string", role: "대기중|승인" },
      { name: "status", type: "string", role: "활성화|비활성" },
      { name: "assignedMatchNumber", type: "string|null", role: "배정 제N경기" },
      { name: "operatorSlot", type: "number|null", role: "운영자 슬롯 번호" },
      { name: "dailyPasswordPlain", type: "string", role: "당일 운영자 비밀번호 평문" },
      { name: "dailyPasswordDate", type: "string", role: "당일 비밀번호 날짜" },
      { name: "loginLinkToken", type: "string", role: "카톡 자동 로그인 토큰" },
      { name: "loginLinkExpiresAt", type: "Date|null", role: "로그인 링크 만료" },
      {
        name: "apiSyncEnabled",
        type: "boolean",
        role: "실황 ON. 다음+네이버 폴링 + 회원 게임 연동. 기본 1경기만 true",
      },
      { name: "apiSyncDefaultPolicy", type: "number", role: "실황 기본값 마이그레이션 버전" },
      { name: "logoutAllowed", type: "boolean", role: "강제 로그아웃 허용" },
      { name: "lastLogin", type: "Date|null", role: "마지막 로그인" },
      { name: "lastLogout", type: "Date|null", role: "마지막 로그아웃" },
      { name: "lastLoginIp", type: "string", role: "로그인 IP" },
      { name: "lastLoginRegion", type: "string", role: "로그인 지역" },
      { name: "notes", type: "string", role: "관리 메모" },
      { name: "createdAt", type: "Date", role: "계정 생성" },
    ],
  },
  {
    area: "콘텐츠",
    model: "Notice",
    collection: "notices",
    role: "공지. 예측 화면 HUD가 아니라 설정·홈에서 봄",
    fields: [
      { name: "id", type: "number", role: "공지 번호" },
      { name: "tag", type: "string", role: "분류 태그" },
      { name: "title", type: "string", role: "제목" },
      { name: "content", type: "string", role: "본문" },
      { name: "displayOrder", type: "number", role: "정렬" },
      { name: "dataSource", type: "string", role: "출처" },
      { name: "createdAt", type: "Date", role: "작성" },
      { name: "updatedAt", type: "Date", role: "수정" },
    ],
  },
  {
    area: "콘텐츠",
    model: "NoticeRead",
    collection: "noticereads",
    role: "공지 읽음·게임 배너 닫기(레거시 배너)",
    fields: [
      { name: "userId", type: "string", role: "users.id" },
      { name: "noticeId", type: "number", role: "notices.id" },
      { name: "readAt", type: "Date|null", role: "읽은 시각" },
      { name: "gameBannerDismissedAt", type: "Date|null", role: "게임 배너 닫기. 현재 게임 배너는 없음" },
      { name: "dismissedAt", type: "Date|null", role: "구필드. gameBannerDismissedAt 사용" },
    ],
    indexes: ["unique(userId, noticeId)"],
  },
  {
    area: "콘텐츠",
    model: "Inquiry",
    collection: "inquiries",
    role: "회원 1:1 문의",
    fields: [
      { name: "id", type: "number", role: "문의 번호" },
      { name: "userId", type: "string", role: "users.id" },
      { name: "category", type: "string", role: "분류" },
      { name: "title", type: "string", role: "제목" },
      { name: "content", type: "string", role: "본문" },
      { name: "status", type: "string", role: "pending|in_progress|resolved" },
      { name: "response", type: "string|null", role: "관리자 답변" },
      { name: "isOfficial", type: "boolean", role: "공식 문의 여부" },
      { name: "dataSource", type: "string", role: "출처" },
      { name: "createdAt", type: "Date", role: "접수" },
    ],
  },
  {
    area: "콘텐츠",
    model: "Post",
    collection: "posts",
    role: "커뮤니티 게시글",
    fields: [
      { name: "id", type: "number", role: "글 번호" },
      { name: "title", type: "string", role: "제목" },
      { name: "content", type: "string", role: "본문" },
      { name: "authorId", type: "string", role: "users.id" },
      { name: "dataSource", type: "string", role: "출처" },
      { name: "isOfficial", type: "boolean", role: "공식 글" },
      { name: "viewCount", type: "number", role: "조회수" },
      { name: "createdAt", type: "Date", role: "작성" },
    ],
  },
  {
    area: "콘텐츠",
    model: "Comment",
    collection: "comments",
    role: "게시글 댓글",
    fields: [
      { name: "id", type: "number", role: "댓글 번호" },
      { name: "postId", type: "number", role: "posts.id" },
      { name: "content", type: "string", role: "본문" },
      { name: "authorId", type: "string", role: "users.id" },
      { name: "createdAt", type: "Date", role: "작성" },
    ],
  },
  {
    area: "콘텐츠",
    model: "Term",
    collection: "terms",
    role: "이용약관·개인정보 처리방침",
    fields: [
      { name: "id", type: "number", role: "약관 번호" },
      { name: "title", type: "string", role: "제목" },
      { name: "content", type: "string", role: "본문 HTML/텍스트" },
      { name: "type", type: "string", role: "service|privacy" },
      { name: "createdAt", type: "Date", role: "작성" },
      { name: "updatedAt", type: "Date", role: "수정" },
    ],
  },
  {
    area: "콘텐츠",
    model: "Faq",
    collection: "faqs",
    role: "자주 묻는 질문",
    fields: [
      { name: "id", type: "number", role: "FAQ 번호" },
      { name: "question", type: "string", role: "질문" },
      { name: "answer", type: "string", role: "답변" },
      { name: "order", type: "number", role: "정렬" },
      { name: "createdAt", type: "Date", role: "작성" },
    ],
  },
  {
    area: "콘텐츠",
    model: "Ebook",
    collection: "ebooks",
    role: "전자책 상품",
    fields: [
      { name: "id", type: "number", role: "전자책 번호" },
      { name: "name", type: "string", role: "제목" },
      { name: "price", type: "number", role: "가격" },
      { name: "createdAt", type: "Date", role: "등록" },
    ],
  },
  {
    area: "콘텐츠",
    model: "EbookPurchase",
    collection: "ebookpurchases",
    role: "전자책 구매 기록",
    fields: [
      { name: "id", type: "number", role: "구매 번호" },
      { name: "userId", type: "string", role: "users.id" },
      { name: "ebookId", type: "number", role: "ebooks.id" },
      { name: "purchasedAt", type: "Date", role: "구매 시각" },
    ],
  },
  {
    area: "홈·광고",
    model: "HomePageSettings",
    collection: "homepagesettings",
    role: "사용자 홈 문구·버튼·게임 안내",
    fields: [
      { name: "id", type: "string", role: "문서 키. 보통 default" },
      { name: "greetingPrefix", type: "string", role: "인사 앞말. 기본 안녕하세요" },
      { name: "subGreeting", type: "string", role: "보조 인사" },
      { name: "buttonText", type: "string", role: "CTA. 기본 예측게임 하러가기" },
      { name: "buttonEnabled", type: "boolean", role: "CTA 노출" },
      { name: "showDate", type: "boolean", role: "홈 날짜 표시" },
      { name: "gameGuideTitle", type: "string", role: "야구 예측 게임이란? 제목" },
      { name: "gameGuideSummary", type: "string", role: "안내 요약" },
      { name: "gameGuideContent", type: "string", role: "안내 본문" },
      { name: "gameGuideEnabled", type: "boolean", role: "안내 섹션 노출" },
      { name: "gameGuideImageUrl", type: "string", role: "안내 이미지" },
      { name: "goodsSectionTitle", type: "string", role: "쇼핑센터 제목" },
      { name: "goodsSectionEnabled", type: "boolean", role: "홈 쇼핑 섹션 노출" },
      { name: "introVideoUrl", type: "string", role: "회사 소개 영상 URL" },
      { name: "shopInquiryEmail", type: "string", role: "몰 문의 이메일" },
      { name: "shopInquiryPhone", type: "string", role: "몰 문의 전화" },
      { name: "updatedAt", type: "Date", role: "수정" },
    ],
  },
  {
    area: "홈·광고",
    model: "WaitingScreen",
    collection: "waitingscreens",
    role: "대기 화면 영상 관리. 예측 7단계 시네마틱과는 별개",
    fields: [
      { name: "id", type: "number", role: "영상 번호" },
      { name: "videoName", type: "string", role: "표시 이름" },
      { name: "displayDuration", type: "number", role: "재생 초. 기본 4" },
      { name: "videoUrl", type: "string", role: "영상 URL" },
      { name: "dataSource", type: "string", role: "출처" },
      { name: "createdAt", type: "Date", role: "등록" },
    ],
  },
  {
    area: "홈·광고",
    model: "Advertisement",
    collection: "advertisements",
    role: "리워드 영상 메타. 예측 중 하단 배너는 사용하지 않음",
    fields: [
      { name: "id", type: "number", role: "광고 번호" },
      { name: "videoName", type: "string", role: "표시 이름" },
      { name: "earnedPoints", type: "number", role: "표시용 포인트. 실제 지급은 운영자 중지/80초 워치독 500P" },
      { name: "videoUrl", type: "string", role: "영상 URL" },
      { name: "dataSource", type: "string", role: "출처" },
      { name: "createdAt", type: "Date", role: "등록" },
    ],
  },
  {
    area: "홈·광고",
    model: "AdViewHistory",
    collection: "adviewhistories",
    role: "광고 시청 기록",
    fields: [
      { name: "id", type: "number", role: "기록 번호" },
      { name: "userId", type: "string", role: "users.id" },
      { name: "advertisementId", type: "number", role: "advertisements.id" },
      { name: "viewedAt", type: "Date", role: "시청 시각" },
    ],
  },
  {
    area: "홈·광고",
    model: "AppAdmobConfig",
    collection: "appadmobconfigs",
    role: "네이티브 AdMob 앱/유닛 ID. 예측 화면 배너 유닛은 넣어도 게임 HUD에 쓰지 않음",
    fields: [
      { name: "id", type: "string", role: "문서 키. 보통 default" },
      { name: "androidAppId", type: "string", role: "Android 앱 ID" },
      { name: "iosAppId", type: "string", role: "iOS 앱 ID" },
      { name: "androidInterstitialAdUnitId", type: "string", role: "Android 전면" },
      { name: "iosInterstitialAdUnitId", type: "string", role: "iOS 전면" },
      { name: "androidRewardedAdUnitId", type: "string", role: "Android 리워드(공수·투수)" },
      { name: "iosRewardedAdUnitId", type: "string", role: "iOS 리워드" },
      { name: "androidBannerAdUnitId", type: "string", role: "Android 배너(게임 미사용)" },
      { name: "iosBannerAdUnitId", type: "string", role: "iOS 배너(게임 미사용)" },
      { name: "updatedAt", type: "Date", role: "수정" },
    ],
  },
  {
    area: "쇼핑몰",
    model: "GoodsCategory",
    collection: "goodscategories",
    role: "몰 카테고리",
    fields: [
      { name: "id", type: "number", role: "분류 번호" },
      { name: "parentId", type: "number|null", role: "상위 분류. null이면 루트" },
      { name: "name", type: "string", role: "분류명" },
      { name: "description", type: "string", role: "설명" },
      { name: "imageUrl", type: "string", role: "이미지" },
      { name: "displayOrder", type: "number", role: "정렬" },
      { name: "isActive", type: "boolean", role: "노출" },
      { name: "createdAt", type: "Date", role: "등록" },
      { name: "updatedAt", type: "Date", role: "수정" },
    ],
    indexes: ["(parentId, displayOrder)"],
  },
  {
    area: "쇼핑몰",
    model: "GoodsProduct",
    collection: "goodsproducts",
    role: "몰 상품. 게임 포인트로 직접 결제하지 않음",
    fields: [
      { name: "id", type: "number", role: "상품 번호" },
      { name: "categoryId", type: "number", role: "goodscategories.id" },
      { name: "name", type: "string", role: "상품명" },
      { name: "summary", type: "string", role: "짧은 설명" },
      { name: "detailContent", type: "string", role: "상세 HTML" },
      { name: "imageUrl", type: "string", role: "대표 이미지" },
      { name: "thumbnailUrl", type: "string", role: "썸네일" },
      { name: "priceLabel", type: "string", role: "표시 가격 문구" },
      { name: "priceAmount", type: "number", role: "판매가(원)" },
      { name: "originalPriceAmount", type: "number", role: "정가(원)" },
      { name: "brand", type: "string", role: "브랜드" },
      { name: "color", type: "string", role: "기본 색상(단일 옵션)" },
      { name: "size", type: "string", role: "기본 사이즈" },
      { name: "stockQuantity", type: "number", role: "재고. -1은 무제한 표시" },
      { name: "variants[]", type: "subdoc[]", role: "color, size, stock 옵션 재고" },
      { name: "fulfillmentType", type: "string", role: "stock=재고판매, procure=발주" },
      { name: "procureNotice", type: "string", role: "발주 안내문" },
      { name: "reorderPoint", type: "number", role: "발주점" },
      { name: "optimalStock", type: "number", role: "적정 재고" },
      { name: "discountPercent", type: "number", role: "할인율" },
      { name: "shippingLabel", type: "string", role: "배송 문구. 기본 무료배송" },
      { name: "detailImages[]", type: "string[]", role: "상세 이미지 URL" },
      { name: "purchaseUrl", type: "string", role: "외부 구매 링크(있으면)" },
      { name: "displayOrder", type: "number", role: "정렬" },
      { name: "isActive", type: "boolean", role: "판매 중" },
      { name: "createdAt", type: "Date", role: "등록" },
      { name: "updatedAt", type: "Date", role: "수정" },
    ],
    indexes: ["(categoryId, displayOrder)"],
  },
  {
    area: "쇼핑몰",
    model: "MallOrder",
    collection: "mallorders",
    role: "현금 주문 접수. 상태 pending→preparing→confirmed→shipped",
    fields: [
      { name: "id", type: "number", role: "주문 번호" },
      { name: "userId", type: "string", role: "users.id" },
      { name: "customerName", type: "string", role: "수령인" },
      { name: "customerPhone", type: "string", role: "연락처" },
      { name: "shippingAddress", type: "string", role: "배송지" },
      { name: "memo", type: "string", role: "요청사항" },
      {
        name: "items[]",
        type: "subdoc[]",
        role: "productId, productName, priceAmount, quantity, imageUrl, color, size",
      },
      { name: "totalAmount", type: "number", role: "합계(원)" },
      { name: "status", type: "string", role: "pending|preparing|confirmed|shipped|cancelled" },
      { name: "courierCompany", type: "string", role: "택배사" },
      { name: "trackingNumber", type: "string", role: "운송장" },
      { name: "shippedAt", type: "Date", role: "발송 시각" },
      { name: "stockRestored", type: "boolean", role: "취소 시 재고 복구 여부" },
      { name: "rewardPointsGranted", type: "boolean", role: "사후 포인트 적립 여부" },
      { name: "rewardPointsAmount", type: "number", role: "적립 포인트" },
      { name: "createdAt", type: "Date", role: "주문" },
      { name: "updatedAt", type: "Date", role: "수정" },
    ],
    indexes: ["(userId, createdAt)", "(status, createdAt)"],
  },
  {
    area: "쇼핑몰",
    model: "MallWishlist",
    collection: "mallwishlists",
    role: "상품 찜",
    fields: [
      { name: "userId", type: "string", role: "users.id" },
      { name: "productId", type: "number", role: "goodsproducts.id" },
      { name: "createdAt", type: "Date", role: "담은 시각" },
    ],
    indexes: ["unique(userId, productId)"],
  },
  {
    area: "쇼핑몰",
    model: "ShopInquiry",
    collection: "shopinquiries",
    role: "상품 문의",
    fields: [
      { name: "id", type: "number", role: "문의 번호" },
      { name: "productId", type: "number", role: "goodsproducts.id" },
      { name: "productName", type: "string", role: "상품명 스냅샷" },
      { name: "customerName", type: "string", role: "문의자" },
      { name: "phone", type: "string", role: "전화" },
      { name: "email", type: "string", role: "이메일" },
      { name: "message", type: "string", role: "문의 내용" },
      { name: "response", type: "string", role: "답변" },
      { name: "respondedAt", type: "Date", role: "답변 시각" },
      { name: "status", type: "string", role: "pending|done" },
      { name: "createdAt", type: "Date", role: "접수" },
      { name: "updatedAt", type: "Date", role: "수정" },
    ],
  },
  {
    area: "쇼핑몰",
    model: "MallProductReview",
    collection: "mallproductreviews",
    role: "상품 리뷰",
    fields: [
      { name: "id", type: "number", role: "리뷰 번호" },
      { name: "productId", type: "number", role: "goodsproducts.id" },
      { name: "authorName", type: "string", role: "작성자 표시명" },
      { name: "rating", type: "number", role: "1~5점" },
      { name: "content", type: "string", role: "본문" },
      { name: "isVisible", type: "boolean", role: "노출" },
      { name: "createdAt", type: "Date", role: "작성" },
    ],
  },
  {
    area: "쇼핑몰",
    model: "MallWarehouse",
    collection: "mallwarehouses",
    role: "창고 마스터",
    fields: [
      { name: "id", type: "number", role: "창고 번호" },
      { name: "name", type: "string", role: "창고명" },
      { name: "isDefault", type: "boolean", role: "기본 창고" },
      { name: "createdAt", type: "Date", role: "등록" },
    ],
  },
  {
    area: "쇼핑몰",
    model: "MallLocation",
    collection: "malllocations",
    role: "창고 로케이션",
    fields: [
      { name: "id", type: "number", role: "로케이션 번호" },
      { name: "warehouseId", type: "number", role: "mallwarehouses.id" },
      { name: "code", type: "string", role: "위치 코드" },
      { name: "description", type: "string", role: "설명" },
      { name: "createdAt", type: "Date", role: "등록" },
    ],
    indexes: ["unique(warehouseId, code)"],
  },
  {
    area: "쇼핑몰",
    model: "MallStockMovement",
    collection: "mallstockmovements",
    role: "재고 이동(입고·출고·이동)",
    fields: [
      { name: "id", type: "number", role: "이동 번호" },
      { name: "warehouseId", type: "number", role: "mallwarehouses.id" },
      { name: "locationId", type: "number", role: "malllocations.id" },
      { name: "productId", type: "number", role: "goodsproducts.id" },
      { name: "productName", type: "string", role: "상품명 스냅샷" },
      { name: "color", type: "string", role: "색상" },
      { name: "size", type: "string", role: "사이즈" },
      { name: "quantity", type: "number", role: "수량. 출고는 음수일 수 있음" },
      { name: "movementType", type: "string", role: "입고·출고·이동 구분" },
      { name: "referenceId", type: "number", role: "주문·발주 참조" },
      { name: "memo", type: "string", role: "메모" },
      { name: "createdAt", type: "Date", role: "처리 시각" },
    ],
  },
  {
    area: "쇼핑몰",
    model: "MallSupplier",
    collection: "mallsuppliers",
    role: "매입처",
    fields: [
      { name: "id", type: "number", role: "매입처 번호" },
      { name: "name", type: "string", role: "상호" },
      { name: "contactName", type: "string", role: "담당자" },
      { name: "phone", type: "string", role: "전화" },
      { name: "email", type: "string", role: "이메일" },
      { name: "memo", type: "string", role: "메모" },
      { name: "createdAt", type: "Date", role: "등록" },
    ],
  },
  {
    area: "쇼핑몰",
    model: "MallPurchaseOrder",
    collection: "mallpurchaseorders",
    role: "발주",
    fields: [
      { name: "id", type: "number", role: "발주 번호" },
      { name: "supplierId", type: "number", role: "mallsuppliers.id" },
      { name: "supplierName", type: "string", role: "매입처 스냅샷" },
      { name: "status", type: "string", role: "draft|ordered|partial|received|cancelled" },
      {
        name: "lines[]",
        type: "subdoc[]",
        role: "productId, productName, color, size, quantity, receivedQuantity, unitCost",
      },
      { name: "memo", type: "string", role: "메모" },
      { name: "orderedAt", type: "Date", role: "발주일" },
      { name: "createdAt", type: "Date", role: "작성" },
      { name: "updatedAt", type: "Date", role: "수정" },
    ],
  },
  {
    area: "소셜",
    model: "FriendRoom",
    collection: "friendrooms",
    role: "친구·동호회 방. 방 전용 경기가 아니라 오늘 공개 예측에 함께 참여",
    fields: [
      { name: "id", type: "string", role: "방 UUID" },
      { name: "name", type: "string", role: "방 이름" },
      { name: "description", type: "string", role: "소개" },
      { name: "supportTeam", type: "string", role: "응원팀. 기본 무관" },
      { name: "ageGroup", type: "string", role: "연령대. 기본 무관" },
      { name: "region", type: "string", role: "지역. 기본 무관" },
      { name: "capacity", type: "number", role: "정원" },
      { name: "hostUserId", type: "string", role: "방장 users.id" },
      { name: "inviteToken", type: "string", role: "초대 토큰", values: "unique" },
      { name: "disclaimerAgreedAt", type: "Date", role: "면책 동의 시각" },
      { name: "createdAt", type: "Date", role: "개설" },
    ],
  },
  {
    area: "소셜",
    model: "FriendRoomMember",
    collection: "friendroommembers",
    role: "방 멤버",
    fields: [
      { name: "id", type: "string", role: "멤버십 UUID" },
      { name: "roomId", type: "string", role: "friendrooms.id" },
      { name: "userId", type: "string", role: "users.id" },
      { name: "role", type: "string", role: "host|member" },
      { name: "joinedAt", type: "Date", role: "입장" },
    ],
    indexes: ["unique(roomId, userId)"],
  },
  {
    area: "소셜",
    model: "FriendRoomAudit",
    collection: "friendroomaudits",
    role: "방 종료 후 면책·부정이용 대응 로그. expiresAt TTL 삭제",
    fields: [
      { name: "id", type: "string", role: "로그 UUID" },
      { name: "hostUserId", type: "string", role: "방장" },
      { name: "roomNameSnapshot", type: "string", role: "종료 시점 방 이름" },
      { name: "disclaimerAgreedAt", type: "Date", role: "면책 동의" },
      { name: "createdAt", type: "Date", role: "개설 시각 스냅샷" },
      { name: "closedAt", type: "Date", role: "종료 시각" },
      { name: "memberCountAtClose", type: "number", role: "종료 시 인원" },
      { name: "expiresAt", type: "Date", role: "TTL. 이 시각 이후 자동 삭제" },
    ],
    indexes: ["TTL(expiresAt)"],
  },
];

export const LIVE_SCOREBOARD_FIELDS: MongoFieldDoc[] = [
  { name: "homeTeamName", type: "string", role: "홈 팀명" },
  { name: "awayTeamName", type: "string", role: "원정 팀명" },
  { name: "homeTeamLogo", type: "string|null", role: "홈 로고 URL(다음 teams.imageUrl)" },
  { name: "awayTeamLogo", type: "string|null", role: "원정 로고 URL" },
  { name: "homeScore", type: "number", role: "홈 점수(다음)" },
  { name: "awayScore", type: "number", role: "원정 점수(다음)" },
  { name: "homeHits", type: "number", role: "홈 안타(다음)" },
  { name: "awayHits", type: "number", role: "원정 안타(다음)" },
  { name: "homeErrors", type: "number", role: "홈 실책(다음)" },
  { name: "awayErrors", type: "number", role: "원정 실책(다음)" },
  { name: "homeWalks", type: "number", role: "홈 볼넷(다음 ballfour). 네이버에서 가져오지 않음" },
  { name: "awayWalks", type: "number", role: "원정 볼넷(다음)" },
  { name: "homeInnings", type: "object", role: "홈 이닝별 득점 맵 {\"1\":0,...}" },
  { name: "awayInnings", type: "object", role: "원정 이닝별 득점 맵" },
  { name: "inning", type: "number|null", role: "이닝. 표시 우선권은 다음 스포츠" },
  { name: "inningHalf", type: "string|null", role: "top=초, bottom=말" },
  { name: "inningLabel", type: "string", role: "N회 초/말 표시 문자열" },
  { name: "statusShort", type: "string", role: "NS, LIVE, FT, BEFORE 등" },
  { name: "statusLong", type: "string", role: "상태 설명" },
  { name: "syncedAt", type: "string", role: "스냅샷 시각 ISO" },
  { name: "situation.balls", type: "number", role: "볼. 네이버. 타석 없으면 가짜 0으로 채우지 않음" },
  { name: "situation.strikes", type: "number", role: "스트라이크. 네이버" },
  { name: "situation.outs", type: "number", role: "실황 아웃. 공수교대 타이밍 가드. 카운트 권위는 Match.outsInHalf" },
  { name: "situation.onFirst", type: "boolean", role: "1루 주자. 네이버" },
  { name: "situation.onSecond", type: "boolean", role: "2루 주자. 네이버" },
  { name: "situation.onThird", type: "boolean", role: "3루 주자. 네이버" },
  { name: "situation.batterName", type: "string", role: "타자명. 네이버" },
  { name: "situation.pitcherName", type: "string", role: "투수명. 네이버" },
  { name: "situation.pitchType", type: "string", role: "구종. 네이버" },
  { name: "situation.batsSide", type: "left|right", role: "타석 손. 포수 시점 배치" },
  { name: "situation.atBatResultDisplay", type: "string", role: "실황 타격 결과 문구" },
];
